const now = new Date();

function minutesAgo(minutes) {
  return new Date(now.getTime() - minutes * 60 * 1000).toISOString();
}

function daysAgo(days) {
  return new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();
}

export const dayZeroLeads = [
  {
    id: 'dz-1',
    nome: 'Maria Souza',
    telefone: '5511991000001',
    canal: 'telegram',
    origem: 'google',
    campanha: 'trabalhista',
    fluxo: 'trabalhista',
    score: 8,
    prioridade: 'QUENTE',
    status: 'NOVO',
    statusFinal: null,
    slaStatus: 'atrasado',
    minutosEspera: 34,
    valorLead: 700,
    valorEntrada: 0,
    valorExito: 0,
    valorEstimado: 700,
    resumo: 'Demitida sem receber rescisão. Quer entrar na Justiça.',
    criadoEm: minutesAgo(34),
    atualizadoEm: minutesAgo(6),
    messages: [
      { id: 'dz-1-m1', direcao: 'in', conteudo: 'Fui demitida e não recebi nada ainda.', criadoEm: minutesAgo(34) },
      { id: 'dz-1-m2', direcao: 'out', conteudo: 'Entendi. Você quer resolver isso judicialmente?', criadoEm: minutesAgo(33) },
      { id: 'dz-1-m3', direcao: 'in', conteudo: 'Sim, quero falar com advogado hoje.', criadoEm: minutesAgo(6) },
    ],
  },
  {
    id: 'dz-2',
    nome: 'João Pereira',
    telefone: '5511991000002',
    canal: 'telegram',
    origem: 'instagram',
    campanha: 'familia',
    fluxo: 'familia',
    score: 4,
    prioridade: 'MEDIO',
    status: 'AGUARDANDO_CLIENTE',
    statusFinal: null,
    slaStatus: 'atencao',
    minutosEspera: 12,
    valorLead: 300,
    valorEntrada: 0,
    valorExito: 0,
    valorEstimado: 300,
    resumo: 'Pensão em atraso. Ainda avaliando próximos passos.',
    criadoEm: minutesAgo(12),
    atualizadoEm: minutesAgo(9),
    messages: [
      { id: 'dz-2-m1', direcao: 'in', conteudo: 'Tenho dúvidas sobre pensão atrasada.', criadoEm: minutesAgo(12) },
      { id: 'dz-2-m2', direcao: 'out', conteudo: 'Isso já está acontecendo ou você quer se organizar?', criadoEm: minutesAgo(11) },
      { id: 'dz-2-m3', direcao: 'in', conteudo: 'Já está acontecendo.', criadoEm: minutesAgo(9) },
    ],
  },
  {
    id: 'dz-3',
    nome: 'Ana Lima',
    telefone: '5511991000003',
    canal: 'telegram',
    origem: 'organico',
    campanha: 'outros',
    fluxo: 'outros',
    score: 2,
    prioridade: 'FRIO',
    status: 'NOVO',
    statusFinal: 'SEM_SUCESSO',
    origemConversao: null,
    slaStatus: 'finalizado',
    minutosEspera: 0,
    valorLead: 180,
    valorEntrada: 0,
    valorExito: 0,
    valorEstimado: 180,
    resumo: 'Abandonou no começo. Reativação enviada, sem resposta.',
    criadoEm: daysAgo(4),
    atualizadoEm: daysAgo(4),
    reativacaoEnviadaEm: daysAgo(1),
    reativacaoRespondidaEm: null,
    messages: [
      { id: 'dz-3-m1', direcao: 'in', conteudo: 'Tenho uma dúvida sobre contrato.', criadoEm: daysAgo(4) },
      { id: 'dz-3-m2', direcao: 'out', conteudo: 'Pode me explicar rapidamente do que se trata?', criadoEm: daysAgo(4) },
      { id: 'dz-3-m3', direcao: 'out', conteudo: 'Vi que você iniciou um atendimento. Posso te ajudar agora?', criadoEm: daysAgo(1) },
    ],
  },
  {
    id: 'dz-4',
    nome: 'Carlos Mendes',
    telefone: '5511991000004',
    canal: 'telegram',
    origem: 'google',
    campanha: 'horas_extras',
    fluxo: 'trabalhista',
    score: 7,
    prioridade: 'QUENTE',
    status: 'EM_ATENDIMENTO',
    statusFinal: 'CONVERTIDO',
    origemConversao: 'atendimento',
    slaStatus: 'finalizado',
    minutosEspera: 0,
    valorLead: 1200,
    valorEntrada: 1200,
    valorExito: 0,
    valorEstimado: 1200,
    resumo: 'Fechou consulta trabalhista direto no primeiro atendimento.',
    criadoEm: minutesAgo(90),
    atualizadoEm: minutesAgo(65),
    messages: [
      { id: 'dz-4-m1', direcao: 'in', conteudo: 'Trabalhei 3 anos sem receber horas extras.', criadoEm: minutesAgo(90) },
      { id: 'dz-4-m2', direcao: 'out', conteudo: 'Seu caso é prioridade. Um advogado vai falar com você.', criadoEm: minutesAgo(89) },
      { id: 'dz-4-m3', direcao: 'in', conteudo: 'Fechado, pode me ligar.', criadoEm: minutesAgo(65) },
    ],
  },
  {
    id: 'dz-5',
    nome: 'Sofia Rocha',
    telefone: '5511991000005',
    canal: 'telegram',
    origem: 'facebook',
    campanha: 'guarda',
    fluxo: 'familia',
    score: 6,
    prioridade: 'QUENTE',
    status: 'EM_ATENDIMENTO',
    statusFinal: 'CONVERTIDO',
    origemConversao: 'reativacao',
    slaStatus: 'finalizado',
    minutosEspera: 0,
    valorLead: 900,
    valorEntrada: 900,
    valorExito: 0,
    valorEstimado: 900,
    resumo: 'Abandonou ontem, respondeu reativação e fechou atendimento.',
    criadoEm: daysAgo(1),
    atualizadoEm: minutesAgo(22),
    reativacaoEnviadaEm: minutesAgo(70),
    reativacaoRespondidaEm: minutesAgo(35),
    messages: [
      { id: 'dz-5-m1', direcao: 'in', conteudo: 'Preciso resolver guarda com urgência.', criadoEm: daysAgo(1) },
      { id: 'dz-5-m2', direcao: 'out', conteudo: 'Isso precisa ser resolvido com urgência?', criadoEm: daysAgo(1) },
      { id: 'dz-5-m3', direcao: 'out', conteudo: 'Vi que você iniciou atendimento. Posso te ajudar agora?', criadoEm: minutesAgo(70) },
      { id: 'dz-5-m4', direcao: 'in', conteudo: 'Sim, ainda preciso. Pode me chamar.', criadoEm: minutesAgo(35) },
    ],
  },
];

export const dayZeroMetrics = {
  tenant: {
    id: 'dia-zero',
    nome: 'Dia Zero Simulado',
    moeda: 'BRL',
    slaMinutes: 15,
    ticketMedio: 1000,
    taxaConversao: 0.2,
    custoMensal: 297,
    metaMensal: 6600,
    metaDiaria: 300,
  },
  leadsHoje: 5,
  leadsMes: 5,
  leadsTotal: 5,
  quentes: 1,
  atrasados: 1,
  potencialHoje: 2500,
  emRisco: 700,
  receitaGerada: 2100,
  receitaFutura: 1000,
  valorMedioLead: 200,
  receitaVsMeta: 0.32,
  lucroEstimado: 2803,
  reativacao: {
    enviados: 2,
    responderam: 1,
    convertidos: 1,
    receitaGerada: 900,
  },
};

export const dayZeroTenantConfig = dayZeroMetrics.tenant;

export function getDayZeroLead(id) {
  return dayZeroLeads.find((lead) => lead.id === id) || null;
}
